import { useCallback, useEffect, useRef, useState } from 'react'
import toast from 'react-hot-toast'
import {
  FileSearch,
  UploadCloud,
  X,
  Loader2,
  FileText,
  FileDown,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
  BookOpen,
  ClipboardList,
  History,
  Trash2,
  RotateCcw,
  Stethoscope,
} from 'lucide-react'
import Card, { CardHeader } from '@/ui/Card'
import Button from '@/ui/Button'
import Badge from '@/ui/Badge'
import Accordion from '@/ui/Accordion'
import EmptyState from '@/ui/EmptyState'
import {
  analyzeDocument,
  getDocumentHistory,
  getDocument,
  deleteDocumentRecord,
  fetchDocumentReportBlob,
} from '@/lib/api'
import { errorMessage, isCanceled, titleCase, formatDate } from '@/lib/utils'

const DOCUMENT_TYPES = [
  { value: 'auto', label: 'Auto-detect' },
  { value: 'handwritten_prescription', label: 'Handwritten Prescription' },
  { value: 'blood_test_report', label: 'Blood Test Report' },
  { value: 'cbc_report', label: 'CBC Report' },
  { value: 'lft_report', label: 'Liver Function Test (LFT)' },
  { value: 'kft_report', label: 'Kidney Function Test (KFT)' },
  { value: 'lipid_profile', label: 'Lipid Profile' },
  { value: 'thyroid_report', label: 'Thyroid Report' },
  { value: 'discharge_summary', label: 'Discharge Summary' },
  { value: 'medical_certificate', label: 'Medical Certificate' },
]

const STATUS_TONE = { high: 'danger', low: 'warning', normal: 'success', unknown: 'neutral' }

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ============================================================
//  Sub-components
// ============================================================
function StatusBadge({ status }) {
  return <Badge tone={STATUS_TONE[status] || 'neutral'}>{titleCase(status || 'unknown')}</Badge>
}

function LabResultsTable({ analysis }) {
  if (!analysis || !analysis.results?.length) {
    return <p className="text-sm text-muted">No structured test rows were detected in this report.</p>
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[520px] text-left text-sm">
        <thead>
          <tr className="border-b border-border text-xs uppercase tracking-wide text-muted">
            <th className="py-2 pr-3 font-medium">Test</th>
            <th className="py-2 pr-3 font-medium">Value</th>
            <th className="py-2 pr-3 font-medium">Reference Range</th>
            <th className="py-2 pr-3 font-medium">Status</th>
          </tr>
        </thead>
        <tbody>
          {analysis.results.map((r, i) => (
            <tr key={i} className="border-b border-border/60 last:border-0">
              <td className="py-2 pr-3 font-medium text-foreground">{r.test_name}</td>
              <td className="py-2 pr-3 text-foreground">{r.value ?? '—'} {r.unit || ''}</td>
              <td className="py-2 pr-3 text-muted">{r.reference_range || 'n/a'}</td>
              <td className="py-2 pr-3"><StatusBadge status={r.status} /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function ClinicalSummaryPanel({ summary }) {
  if (!summary) return null
  return (
    <Card>
      <CardHeader icon={Sparkles} title="AI Clinical Summary" subtitle={`Generated by: ${summary.provider || 'offline'}`} />
      <p className="text-sm text-foreground">{summary.summary}</p>

      {summary.abnormal_findings?.length > 0 && (
        <div className="mt-4">
          <p className="text-[11px] font-medium uppercase tracking-wide text-muted">Abnormal Findings</p>
          <ul className="mt-1.5 space-y-1.5">
            {summary.abnormal_findings.map((f, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                <AlertTriangle size={14} className="mt-0.5 shrink-0 text-warning" />
                {f}
              </li>
            ))}
          </ul>
        </div>
      )}

      {summary.possible_meanings?.length > 0 && (
        <div className="mt-4">
          <p className="text-[11px] font-medium uppercase tracking-wide text-muted">Possible Clinical Meaning</p>
          <div className="mt-1.5 space-y-2">
            {summary.possible_meanings.map((m, i) => (
              <div key={i} className="rounded-xl bg-surface-2 p-3">
                <p className="text-sm font-semibold text-foreground">{m.finding}</p>
                <p className="mt-0.5 text-sm text-muted">{m.meaning}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {summary.ai_explanation && (
        <div className="mt-4">
          <p className="text-[11px] font-medium uppercase tracking-wide text-muted">AI Explanation</p>
          <p className="mt-1 text-sm text-foreground">{summary.ai_explanation}</p>
        </div>
      )}

      {summary.follow_up_suggestions?.length > 0 && (
        <div className="mt-4">
          <p className="text-[11px] font-medium uppercase tracking-wide text-muted">Follow-up Suggestions</p>
          <ul className="mt-1.5 space-y-1">
            {summary.follow_up_suggestions.map((f, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                <CheckCircle2 size={14} className="mt-0.5 shrink-0 text-success" />
                {f}
              </li>
            ))}
          </ul>
        </div>
      )}

      {summary.safety_note && (
        <p className="mt-4 rounded-xl bg-surface-2 p-3 text-xs text-muted">{summary.safety_note}</p>
      )}
    </Card>
  )
}

function EvidenceSourcesPanel({ summary }) {
  if (!summary?.sources?.length) return null
  return (
    <Card>
      <CardHeader
        icon={BookOpen}
        title="Evidence Sources"
        subtitle={`Retrieval confidence: ${Math.round((summary.confidence || 0) * 100)}%`}
      />
      <div className="flex flex-wrap gap-1.5">
        {summary.sources.map((s, i) => (
          <Badge key={i} tone="primary">{s}</Badge>
        ))}
      </div>
    </Card>
  )
}

function StructuredFieldsPanel({ fields }) {
  if (!fields) return null
  const common = [
    ['Patient', fields.patient_name],
    ['Age', fields.age],
    ['Gender', fields.gender],
    ['Date', fields.date],
    ['Doctor', fields.doctor],
    ['Hospital', fields.hospital],
  ].filter(([, v]) => v)
  const sectionEntries = Object.entries(fields.sections || {})

  if (!common.length && !sectionEntries.length) return null

  return (
    <Card>
      <CardHeader icon={ClipboardList} title="Extracted Data" subtitle="Structured fields detected in the document" />
      {common.length > 0 && (
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
          {common.map(([label, val]) => (
            <div key={label} className="rounded-xl bg-surface-2 p-3">
              <p className="text-[11px] font-medium uppercase tracking-wide text-muted">{label}</p>
              <p className="mt-1 text-sm font-semibold text-foreground">{val}</p>
            </div>
          ))}
        </div>
      )}
      {sectionEntries.length > 0 && (
        <div className="mt-4 space-y-3">
          {sectionEntries.map(([heading, text]) => (
            <div key={heading}>
              <p className="text-[11px] font-medium uppercase tracking-wide text-muted">{heading}</p>
              <p className="mt-0.5 text-sm text-foreground">{text}</p>
            </div>
          ))}
        </div>
      )}
    </Card>
  )
}

// ============================================================
//  Page
// ============================================================
export default function DocumentIntelligence() {
  const [file, setFile] = useState(null)
  const [preview, setPreview] = useState(null)
  const [dragOver, setDragOver] = useState(false)
  const [documentType, setDocumentType] = useState('auto')
  const [progress, setProgress] = useState(0)
  const [processing, setProcessing] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState(null)
  const [downloading, setDownloading] = useState(false)
  const [history, setHistory] = useState([])
  const [historyLoading, setHistoryLoading] = useState(false)
  const inputRef = useRef(null)
  const abortRef = useRef(null)

  const loadHistory = useCallback(async () => {
    setHistoryLoading(true)
    try {
      const page = await getDocumentHistory({ page: 1, page_size: 8 })
      setHistory(page.items || [])
    } catch {
      // Best-effort — history is a convenience panel, not core to the page.
    } finally {
      setHistoryLoading(false)
    }
  }, [])

  // Fetch-on-mount: setState happens after the request resolves, which is the
  // canonical pattern for fetch-on-mount/deps.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { loadHistory() }, [loadHistory])

  const pickFile = (f) => {
    if (!f) return
    const isImage = f.type.startsWith('image/')
    const isPdf = f.type === 'application/pdf' || f.name?.toLowerCase().endsWith('.pdf')
    if (!isImage && !isPdf) return toast.error('Please choose an image or PDF file')
    setFile(f)
    setPreview(isImage ? URL.createObjectURL(f) : null)
    setResult(null)
    setError(null)
  }
  const onDrop = (e) => { e.preventDefault(); setDragOver(false); pickFile(e.dataTransfer.files?.[0]) }
  const reset = () => {
    setFile(null); setPreview(null); setResult(null); setError(null); setProgress(0)
  }

  const run = async () => {
    if (!file) return
    const controller = new AbortController()
    abortRef.current = controller
    setProcessing(true); setError(null); setResult(null); setProgress(0)
    try {
      const data = await analyzeDocument(file, {
        documentType,
        onProgress: setProgress,
        signal: controller.signal,
      })
      setResult(data)
      loadHistory()
    } catch (err) {
      if (!isCanceled(err)) {
        setError(errorMessage(err, 'We could not analyze this document. Please try again.'))
      }
    } finally {
      setProcessing(false)
      abortRef.current = null
    }
  }

  const cancel = () => abortRef.current?.abort()

  const openHistoryItem = async (id) => {
    try {
      const detail = await getDocument(id)
      setFile(null); setPreview(null); setError(null)
      setResult({ ...detail })
    } catch (err) {
      toast.error(errorMessage(err, 'Could not load this record.'))
    }
  }

  const removeHistoryItem = async (id, e) => {
    e.stopPropagation()
    try {
      await deleteDocumentRecord(id)
      setHistory((prev) => prev.filter((h) => h.id !== id))
    } catch (err) {
      toast.error(errorMessage(err, 'Could not delete this record.'))
    }
  }

  const downloadReport = async () => {
    if (!result?.id) {
      toast.error('This analysis has not been saved yet.')
      return
    }
    setDownloading(true)
    try {
      const blob = await fetchDocumentReportBlob(result.id)
      downloadBlob(`medisense-document-${result.id}.json`, blob)
    } catch (err) {
      toast.error(errorMessage(err, 'Could not download the report.'))
    } finally {
      setDownloading(false)
    }
  }

  return (
    <div className="grid gap-6 lg:grid-cols-5">
      {/* Upload panel */}
      <div className="lg:col-span-2">
        <Card className="lg:sticky lg:top-24">
          <CardHeader
            icon={FileSearch}
            title="Medical Document Intelligence"
            subtitle="Upload a prescription, lab report, discharge summary or certificate"
          />

          {!preview && !(file && !file.type.startsWith('image/')) ? (
            <div
              role="button" tabIndex={0}
              onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={onDrop}
              onClick={() => inputRef.current?.click()}
              onKeyDown={(e) => e.key === 'Enter' && inputRef.current?.click()}
              className={`flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-10 text-center transition-colors ${
                dragOver ? 'border-primary bg-primary-soft' : 'border-border hover:border-primary/50 hover:bg-surface-2'
              }`}
            >
              <span className="grid h-14 w-14 place-items-center rounded-2xl bg-primary-soft text-primary"><UploadCloud size={26} /></span>
              <p className="mt-3 font-medium text-foreground">Drag & drop, or click to browse</p>
              <p className="mt-1 text-xs text-muted">JPG, PNG, WEBP or PDF</p>
            </div>
          ) : (
            <div className="relative overflow-hidden rounded-2xl border border-border">
              {preview ? (
                <img src={preview} alt="Document preview" className="max-h-72 w-full bg-surface-2 object-contain" />
              ) : (
                <div className="flex items-center gap-3 bg-surface-2 p-6">
                  <FileText size={28} className="text-primary" />
                  <span className="truncate text-sm font-medium text-foreground">{file?.name}</span>
                </div>
              )}
              <button onClick={reset} aria-label="Remove file" className="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-full bg-black/60 text-white hover:bg-black/80"><X size={16} /></button>
              {processing && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-background/85 backdrop-blur-sm">
                  <Loader2 size={32} className="animate-spin text-primary" />
                  <p className="text-sm font-medium text-foreground">{progress < 100 ? `Uploading ${progress}%` : 'Analyzing document…'}</p>
                  <Button size="sm" variant="secondary" onClick={cancel}><X size={14} /> Cancel</Button>
                </div>
              )}
            </div>
          )}
          <input ref={inputRef} type="file" accept="image/*,application/pdf" hidden onChange={(e) => pickFile(e.target.files?.[0])} />

          <div className="mt-4">
            <label className="text-[11px] font-medium uppercase tracking-wide text-muted">Document type</label>
            <select
              value={documentType}
              onChange={(e) => setDocumentType(e.target.value)}
              className="mt-1 h-10 w-full rounded-xl border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-primary"
            >
              {DOCUMENT_TYPES.map((t) => (
                <option key={t.value} value={t.value}>{t.label}</option>
              ))}
            </select>
          </div>

          <Button className="mt-4 w-full" onClick={run} loading={processing} disabled={!file}>
            <FileSearch size={16} /> Analyze Document
          </Button>
          <p className="mt-3 text-xs text-muted">
            Auto-detect works from the document's own content — override it above if it guesses wrong.
          </p>
        </Card>

        {/* Recent documents */}
        <Card className="mt-5">
          <CardHeader icon={History} title="Recent Documents" />
          {historyLoading ? (
            <p className="text-sm text-muted">Loading…</p>
          ) : history.length === 0 ? (
            <p className="text-sm text-muted">No documents analyzed yet.</p>
          ) : (
            <div className="space-y-1.5">
              {history.map((h) => (
                <button
                  key={h.id}
                  onClick={() => openHistoryItem(h.id)}
                  className="flex w-full items-center justify-between gap-2 rounded-xl px-2.5 py-2 text-left text-sm hover:bg-surface-2"
                >
                  <span className="min-w-0">
                    <span className="block truncate font-medium text-foreground">{h.filename || 'Untitled'}</span>
                    <span className="block text-xs text-muted">
                      {titleCase(h.document_type)} · {formatDate(h.created_at)}
                      {h.abnormal_count > 0 && <span className="text-warning"> · {h.abnormal_count} abnormal</span>}
                    </span>
                  </span>
                  <span
                    role="button"
                    tabIndex={0}
                    onClick={(e) => removeHistoryItem(h.id, e)}
                    aria-label="Delete record"
                    className="shrink-0 rounded-lg p-1.5 text-muted hover:bg-danger/10 hover:text-danger"
                  >
                    <Trash2 size={14} />
                  </span>
                </button>
              ))}
            </div>
          )}
        </Card>
      </div>

      {/* Results */}
      <div className="space-y-5 lg:col-span-3">
        {error && (
          <Card className="border-danger/40 bg-danger/5">
            <div className="flex items-center justify-between gap-3">
              <p className="text-sm text-foreground">{error}</p>
              <Button variant="secondary" size="sm" onClick={reset}><RotateCcw size={14} /> Retry</Button>
            </div>
          </Card>
        )}

        {!result && !processing && !error && (
          <EmptyState
            icon={Stethoscope}
            title="No document analyzed yet"
            description="Upload a prescription, lab report, discharge summary or medical certificate to get started."
          />
        )}

        {result && (
          <>
            <Card>
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h2 className="text-lg font-bold text-foreground">{result.filename || 'Document'}</h2>
                  <div className="mt-1 flex flex-wrap items-center gap-2">
                    <Badge tone="primary">{titleCase(result.document_type)}</Badge>
                    {result.classification && (
                      <span className="text-xs text-muted">
                        {result.classification.auto_detected ? 'Auto-detected' : 'Manually set'} ·{' '}
                        {Math.round((result.classification.confidence || 0) * 100)}% confidence
                      </span>
                    )}
                  </div>
                </div>
                <Button variant="secondary" size="sm" onClick={downloadReport} loading={downloading}>
                  <FileDown size={14} /> Download Structured Report
                </Button>
              </div>

              {result.warnings?.length > 0 && (
                <div className="mt-4 space-y-1.5">
                  {result.warnings.map((w, i) => (
                    <div key={i} className="flex items-start gap-2 rounded-xl bg-warning/10 p-2.5 text-sm text-foreground">
                      <AlertTriangle size={14} className="mt-0.5 shrink-0 text-warning" />
                      {w}
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {result.lab_analysis && (
              <Card>
                <CardHeader
                  icon={Stethoscope}
                  title="Lab Results"
                  subtitle={`${result.lab_analysis.abnormal_count} of ${result.lab_analysis.total_count} value(s) outside reference range`}
                />
                <LabResultsTable analysis={result.lab_analysis} />
              </Card>
            )}

            <StructuredFieldsPanel fields={result.fields} />

            {result.raw_text && (
              <Accordion title="Extracted Text" subtitle="Raw text from OCR / PDF extraction" icon={FileText}>
                <pre className="whitespace-pre-wrap break-words text-sm text-muted">{result.raw_text}</pre>
              </Accordion>
            )}

            <ClinicalSummaryPanel summary={result.clinical_summary} />
            <EvidenceSourcesPanel summary={result.clinical_summary} />
          </>
        )}
      </div>
    </div>
  )
}
